update name json

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,17 +23,31 @@ jobs:
         tar -zxf image-syncer-v1.5.5-linux-amd64.tar.gz
       
     - name: 执行同步镜像
+      id: sync
       run: |
         ./image-syncer --proc=20 --config=config.json --retries=2
+        if [ $? -eq 0 ]; then
+          echo "sync_status=success" >> $GITHUB_ENV
+          echo "镜像名称: docker.io/nginx, 版本: latest" >> $GITHUB_ENV
+        else
+          echo "sync_status=failure" >> $GITHUB_ENV
+          echo "镜像名称: docker.io/nginx, 版本: latest" >> $GITHUB_ENV
+        fi
 
     - name: 发送钉钉通知
       run: |
+        if [ "${{ env.sync_status }}" == "success" ]; then
+          message="镜像同步成功！镜像名称: ${IMAGE_NAME}, 版本: ${IMAGE_VERSION}"
+        else
+          message="镜像同步失败！镜像名称: ${IMAGE_NAME}, 版本: ${IMAGE_VERSION}"
+        fi
+
         curl -X POST https://oapi.dingtalk.com/robot/send?access_token=2dd786ab5ee396d7c2d96877585467daa0c67b62546b5a550da948f1d856463b \
         -H 'Content-Type: application/json' \
         -d '{
           "msgtype": "text",
           "text": {
-            "content": "镜像同步完成！"
+            "content": "'"${message}"'"
           },
           "at": {
             "isAtAll": true
